site_name: 써드아이시스템 기술문서
site_url: 'https://tech.3rdeyesys.com'


theme:
  name: material
  language: kr

  palette:
    scheme: default
    primary: green
  favicon: assets/favicon.png


plugins:
    - search
    - awesome-pages
    
markdown_extensions:
    - smarty
    
    
edit_uri: docs/
